#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
mapfile -t CLASSIFIERS <"${DIR}/tag-classifiers.txt"
mapfile -t VERSIONS <"${DIR}/tag-versions.txt"
declare -a TAGS
TAGS+=( "${CLASSIFIERS[@]}" )
TAGS+=( "${VERSIONS[@]}" )
for VERSION in "${VERSIONS[@]}"; do
  for CLASSIFIER in "${CLASSIFIERS[@]}"; do
    TAGS+=( "${VERSION}-${CLASSIFIER}" )
  done
done
GENDIR="${DIR}/generated"
mkdir -p "${GENDIR}"
for TAGIDX in "${!TAGS[@]}"; do
  TAG="${TAGS[$TAGIDX]}"
  TAGCNT=$((TAGIDX+1))
  DOCKERFILE="${GENDIR}/Dockerfile-${TAG}"
  echo "  FROM php:${TAG}" >"${DOCKERFILE}"
  cat "${DIR}/Dockerfile" >>"${DOCKERFILE}"
  echo
  echo
  echo "/-----------------------"
  echo "/ DOCKER BUILD (${TAGCNT}/${#TAGS[@]}) ${TAG}"
  echo "/"
  docker build "${DIR}" -f "${DOCKERFILE}" -t "${DOCKER_REPO}:${TAG}"
  echo "|"
  echo "| DOCKER BUILD FINISHED"
  echo "|-----------------------"
  echo "| DOCKER PUSH (${TAGCNT}/${#TAGS[@]}) ${TAG}"
  echo "|"
  docker push "${DOCKER_REPO}:${TAG}"
  echo "\\"
  echo "\\ DOCKER PUSH FINISHED"
  echo "\\-----------------------"
  echo
done

